### ISSUE TITLE
Update sanitize-html

### ISSUE THREAD

**Issue by alann-sapone** [leopiccionia/vue-sanitize-directive#1]
It might be interesting to update sanitize-html to increase the audit quality : https://github.com/apostrophecms/sanitize-html/pull/458

**Comment by leopiccionia** [comment]
I wasn't using this library lately, but I think I can use some time (perhaps next weekend) to release a new version.

For future reference, I'll try to accomplish these:
- Migrate to latest `sanitize-html` 2.x (there are other interesting improvements, like apostrophecms/sanitize-html#393);
- ~~Make `sanitize-html` a peer dependency, for easier future upgrading~~ Nevermind, preparing `sanitize-html` for use in the browser is not trivial;
- Audit and bump dependencies in general;
- Simultaneous support for both Vue 2.x and Vue 3.x (it seems easier than it sounds);
- Experimental support for SSR (I'm not sure the Vue 3.x `getSSRProps` allows this usage).

I think there won't be breaking changes apart from new `sanitize-html` version and its new defaults.

**Comment by leopiccionia** [comment]
I'm closing it because 0.2.0 release uses `sanitize-html` 2.7.0.
